In [4]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[2,12,23,10,89]])
print(arr)
print('0th element on 2nd row: ', arr[1,9])
#4th element on 1 row
#3th element on 0th row

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]


IndexError: index 9 is out of bounds for axis 1 with size 5

In [5]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[2,12,23,10,89]])
print(arr)
print('0th element on 2nd row: ', arr[1,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]
0th element on 2nd row:  9


In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[2,12,23,10,89]])
print(arr)
print('0th element on 2nd row: ', arr[2,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]
0th element on 2nd row:  89


In [7]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr[1:5:2])

[2 4]


In [10]:
import pandas as pd

data = {
    "Name": ["John", "Alice", "Bob", "Diana"],
    "Age": [28, 34, 23, 29],
    "Department": ["HR", "IT", "Marketing", "Finance"],
    "Salary": [45000, 60000, 35000, 50000]
}
Marks = {
    "Name":["john","joy"],
    "AI":[12,15],
    "ML":[15,14]
}



df = pd.DataFrame(data)
df1=pd.DataFrame(Marks)

print(df)
print(df1)

    Name  Age Department  Salary
0   John   28         HR   45000
1  Alice   34         IT   60000
2    Bob   23  Marketing   35000
3  Diana   29    Finance   50000
   Name  AI  ML
0  john  12  15
1   joy  15  14


In [11]:
print(df.describe())
print(df1.describe())
print(df.shape)
print(df1.shape)
print(df.loc[2])
print(df1.loc[1])

            Age        Salary
count   4.00000      4.000000
mean   28.50000  47500.000000
std     4.50925  10408.329997
min    23.00000  35000.000000
25%    26.75000  42500.000000
50%    28.50000  47500.000000
75%    30.25000  52500.000000
max    34.00000  60000.000000
             AI         ML
count   2.00000   2.000000
mean   13.50000  14.500000
std     2.12132   0.707107
min    12.00000  14.000000
25%    12.75000  14.250000
50%    13.50000  14.500000
75%    14.25000  14.750000
max    15.00000  15.000000
(4, 4)
(2, 3)
Name                Bob
Age                  23
Department    Marketing
Salary            35000
Name: 2, dtype: object
Name    joy
AI       15
ML       14
Name: 1, dtype: object
